"""
Deterministic (non-LLM) nutrition advisory. It only reasons over numbers we
already have — today's logged totals plus this item's totals — checked
against general public-health guidelines. Deliberately NOT generated by the
model: for a numeric threshold check, a rule is more reliable and cheaper
than asking an LLM to do arithmetic, and it can't hallucinate a number.

This is general informational guidance based on the person's own data, not
personalized medical advice, and is presented to the user as such.
"""

DAILY_SUGAR_LIMIT_G = 50.0       # WHO general upper bound for free sugars/day
DAILY_SODIUM_LIMIT_MG = 2300.0   # WHO / ICMR general upper bound/day


def build_advisory(today_totals: dict, item_calories: float,
                    item_sugar_g: float | None, item_sodium_mg: float | None) -> str:
    sugar_so_far = today_totals.get("total_sugar_g") or 0.0
    sodium_so_far = today_totals.get("total_sodium_mg") or 0.0
    calories_so_far = today_totals.get("total_calories") or 0.0

    lines: list[str] = []

    if item_sugar_g is not None:
        projected_sugar = sugar_so_far + item_sugar_g
        if projected_sugar > DAILY_SUGAR_LIMIT_G:
            lines.append(
                f"You've already logged about {sugar_so_far:.0f}g of sugar today. "
                f"This item adds ~{item_sugar_g:.0f}g, taking you to ~{projected_sugar:.0f}g — "
                f"over the general {DAILY_SUGAR_LIMIT_G:.0f}g/day guideline. Worth skipping "
                f"this one or having a smaller portion."
            )
        else:
            remaining = DAILY_SUGAR_LIMIT_G - projected_sugar
            lines.append(
                f"Sugar today: ~{sugar_so_far:.0f}g logged so far, this adds ~{item_sugar_g:.0f}g "
                f"(~{projected_sugar:.0f}g total) — still within the general "
                f"{DAILY_SUGAR_LIMIT_G:.0f}g/day guideline, about {remaining:.0f}g of headroom left."
            )

    if item_sodium_mg is not None:
        projected_sodium = sodium_so_far + item_sodium_mg
        if projected_sodium > DAILY_SODIUM_LIMIT_MG:
            lines.append(
                f"Sodium would reach ~{projected_sodium:.0f}mg today, over the general "
                f"{DAILY_SODIUM_LIMIT_MG:.0f}mg/day guideline."
            )

    lines.append(f"Calories logged today before this item: ~{calories_so_far:.0f} kcal.")
    lines.append(
        "This is general guidance based on your own logged data against public-health "
        "guidelines, not personalized medical advice — check with a doctor or dietitian "
        "for advice specific to you."
    )

    return " ".join(lines)
